### ISSUE TITLE
Making xpipe app more obvious

### ISSUE THREAD

**Issue by hucknz** [xpipe-io/xpipe-webtop#1]
Hey, thanks so much for publishing this as a container image. So far it seems great, one question I have is whether there is a way you could pin the application to the menu bar or open it by default?

I'm not familiar with that desktop environment and initially I thought xpipe wasn't installed. It took me a beat to realise that there was a menu and xpipe was in there. I imagine others may find themselves wondering where it is too.

**Comment by crschnick** [comment]
Yeah I can do that. Just need to figure out how to configure this in the Dockerfile setup

**Comment by crschnick** [comment]
Can you try the new :latest tag release?

**Comment by hucknz** [comment]
Just pulled that down and I can see the app is on the main menu now. Thanks for the fast work!
