### ISSUE TITLE
Use as workspace in Kasm Workspaces

### ISSUE THREAD

**Issue by bannert1337** [xpipe-io/xpipe-webtop#2]
I added XPipe Webtop as a custom workspace to Kasm, but it won't open.
Has anyone else tried this yet?

**Comment by crschnick** [comment]
Can you elaborate on what you mean? I'm not very familiar with KASM and it's full functionality

**Comment by crschnick** [comment]
Also, for any kind of troubleshooting, there are debug scripts available at `/opt/xpipe/app/scripts/xpiped_debug.sh`

**Comment by crschnick** [comment]
Closing this as inactive

**Comment by crschnick** [comment]
There is https://github.com/xpipe-io/kasm-registry now
